CREATE PROCEDURE [dbo].[CreateProduct]
	@Name nvarchar(100),
	@Price decimal,
	@Brand nvarchar(50),
	@Description nvarchar(1000),
	@ManufactureCountry nvarchar(50),
	@ManufactureDate date,
	@Weight float,
	@Wattage int,
	@NoiseLevel int,
	@PresetPrograms int = null,
	@Width float,
	@Height float,
	@Depth float,
	@ScreenSize float = null,
	@Resolution nvarchar(20) = null,
	@DysplayType nvarchar(10) = null,
	@ThreedimensionalTechnology bit = null,
	@WetCleaning bit = null,
	@DustContainerVolume float = null,
	@AttachmentsCount int = null,
	@RemoteLaunch bit = null,
	@СleaningАrea int = null,
	@TurnTableDiameter float = null,
	@NumberOfProwerLevel int = null,
	@Grill bit = null,
	@MicrowavesPower int = null,
	@SimCardCount int = null,
	@FrontСamera bit = null,
	@HeadphoneJack bit = null,
	@BatteryCapacity int = null,
	@ConnectionStandard nvarchar(20) = null,
	@MinTemperatureFreezer int = null,
	@ColdStorageTime int = null,
	@Freezer bit = null,
	@Defrost bit = null
	
	As
	Begin
		insert into [dbo].[Product] (
			Name,
			Price,
			Brand,
			Description,
			ManufactureCountry,
			ManufactureDate,
			Weight,
			Wattage,
			NoiseLevel,
			PresetPrograms,
			Width,
			Height,
			Depth,
			ScreenSize,
			Resolution,
			DysplayType,
			ThreedimensionalTechnology,
			WetCleaning,
			DustContainerVolume,
			AttachmentsCount,
			RemoteLaunch,
			СleaningАrea,
			TurnTableDiameter,
			NumberOfProwerLevel,
			Grill,
			MicrowavesPower,
			SimCardCount,
			FrontСamera,
			HeadphoneJack,
			BatteryCapacity,
			ConnectionStandard,
			MinTemperatureFreezer,
			ColdStorageTime,
			Freezer,
			Defrost)
		values(
		@Name,
		@Price,
		@Brand,
		@Description,
		@ManufactureCountry,
		@ManufactureDate,
		@Weight,
		@Wattage,
		@NoiseLevel,
		@PresetPrograms,
		@Width,
		@Height,
		@Depth,
		@ScreenSize,
		@Resolution,
		@DysplayType,
		@ThreedimensionalTechnology,
		@WetCleaning,
		@DustContainerVolume,
		@AttachmentsCount,
		@RemoteLaunch,
		@СleaningАrea,
		@TurnTableDiameter,
		@NumberOfProwerLevel,
		@Grill,
		@MicrowavesPower,
		@SimCardCount,
		@FrontСamera,
		@HeadphoneJack,
		@BatteryCapacity,
		@ConnectionStandard,
		@MinTemperatureFreezer,
		@ColdStorageTime,
		@Freezer,
		@Defrost)
declare @ProductId int
set @ProductId = SCOPE_IDENTITY()
exec [dbo].[Product_SelectById] @ProductId
end