CREATE PROCEDURE [dbo].[UpdateProductById]
	@Id int,
	@Name nvarchar(100),
	@Price decimal,
	@Brand nvarchar(50),
	@Description nvarchar(1000),
	@ManufactureCountry nvarchar(50),
	@ManufactureDate date,
	@Weight float,
	@Wattage int,
	@NoiseLevel int,
	@PresetPrograms int = null,
	@Width float,
	@Height float,
	@Depth float,
	@ScreenSize float = null,
	@Resolution nvarchar(20) = null,
	@DysplayType nvarchar(10) = null,
	@ThreedimensionalTechnology bit = null,
	@WetCleaning bit = null,
	@DustContainerVolume float = null,
	@AttachmentsCount int = null,
	@RemoteLaunch bit = null,
	@СleaningАrea int = null,
	@TurnTableDiameter float = null,
	@NumberOfProwerLevel int = null,
	@Grill bit = null,
	@MicrowavesPower int = null,
	@SimCardCount int = null,
	@FrontСamera bit = null,
	@HeadphoneJack bit = null,
	@BatteryCapacity int = null,
	@ConnectionStandard nvarchar(20) = null,
	@MinTemperatureFreezer int = null,
	@ColdStorageTime int = null,
	@Freezer bit = null,
	@Defrost bit = null
as 
	begin
	  Update [dbo].[Product] set
	  Name = @Name,
	  Price = @Price,
	  Brand = @Brand,
	  Description = @Description,
	  ManufactureCountry = @ManufactureCountry,
	  ManufactureDate = @ManufactureDate,
	  Weight = @Weight,
	  Wattage = @Wattage,
	  NoiseLevel = @NoiseLevel,
	  PresetPrograms = @PresetPrograms,
	  Width = @Width,
	  Height = @Height,
	  Depth = @Depth,
	  ScreenSize = @ScreenSize,
	  Resolution = @Resolution,
	  DysplayType = @DysplayType,
	  ThreedimensionalTechnology = @ThreedimensionalTechnology,
	  WetCleaning = @WetCleaning,
	  DustContainerVolume = @DustContainerVolume,
	  AttachmentsCount = @AttachmentsCount,
	  RemoteLaunch = @RemoteLaunch,
	  CleaningArea = @СleaningАrea,
	  TurnTableDiameter = @TurnTableDiameter,
	  NumberOfProwerLevel = @NumberOfProwerLevel,
	  Grill = @Grill,
	  MicrowavesPower = @MicrowavesPower,
	  SimCardCount = @SimCardCount,
	  FrontCamera = @FrontСamera,
	  HeadphoneJack = @HeadphoneJack,
	  BatteryCapacity = @BatteryCapacity,
   	  ConnectionStandard = @ConnectionStandard,
	  MinTemperatureFreezer = @MinTemperatureFreezer,
	  ColdStorageTime = @ColdStorageTime,
	  Freezer = @Freezer,
	  Defrost = @Defrost
	  where (Id = @Id)
      exec [dbo].[Product_SelectById] @Id
    end
