CREATE TABLE [dbo].[Product]
(
    [Id] int PRIMARY KEY Identity(1,1) NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[Price] DECIMAL NOT NULL,
	[Brand] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(1000) NOT NULL,
	[ManufactureCountry] NVARCHAR(50) NOT NULL,
	[ManufactureYear] DATETIME2 NOT NULL,
	[Weight] FLOAT NOT NULL,
	[Color] nvarchar(50) NOT NULL, 
	[Wattage] int NOT NULL,
	[NoiseLevel] int NOT NULL,
	[PresetPrograms] int,
	[Width] float NOT NULL,
    [Height] float NOT NULL,
	[Depth] float NOT NULL,
	[ScreenSize] float,
	[Resolution] int,
	[DysplayType] nvarchar(10),
	[3dTechnology] bit,
	[WetCleaning] bit,
	[DustContainerVolume] float,
	[AttachmentsCount] int,
	[RemoteLaunch] int,
	[СleaningАrea] int,
	[TurntableDiameter] float,
	[NumberOfProwerLevel] int,
	[Grill] bit,
	[MicrowavesPower] int,
	[SimCard] bit,
	[FrontСamera] bit,
	[HeadphoneJack] bit,
	[ConnectionStandard] nvarchar,
	[MinTemperatureFreezer] int,
	[ColdStorageTime] int,
	[Freezer] bit,
	[Defrost] bit
)
