CREATE TABLE [dbo].[Product]
(
    [Id] int PRIMARY KEY Identity(1,1) NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[Price] DECIMAL NOT NULL,
	[Brand] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(1000) NOT NULL,
	[ManufactureCountry] NVARCHAR(50) NOT NULL,
	[ManufactureDate] DATE NOT NULL,
	[Weight] FLOAT NOT NULL,
	[Wattage] int  NULL,
	[NoiseLevel] int NOT NULL,
	[PresetPrograms] int,
	[Width] float NOT NULL,
    [Height] float NOT NULL,
	[Depth] float NOT NULL,
	[ScreenSize] float NULL,
	[Resolution] nvarchar(20) NULL,
	[DysplayType] nvarchar(10) NULL,
	[ThreedimensionalTechnology] bit NULL,
	[WetCleaning] bit NULL,
	[DustContainerVolume] float NULL,
	[AttachmentsCount] int NULL,
	[RemoteLaunch] bit NULL,
	[СleaningАrea] int NULL,
	[TurnTableDiameter] float NULL,
	[NumberOfProwerLevel] int NULL,
	[Grill] bit NULL,
	[MicrowavesPower] int NULL,
	[SimCardCount] int NULL,
	[FrontCamera] bit NULL,
	[HeadphoneJack] bit NULL,
	[BatteryCapacity] int NULL,
	[ConnectionStandard] nvarchar(20) NULL,
	[MinTemperatureFreezer] int NULL,
	[ColdStorageTime] int NULL,
	[Freezer] bit NULL,
	[Defrost] bit NULL
)
